server:
  port: 8080

app:
  api-prefix: /api/v1

spring:
  main:
    banner-mode: off
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:9001
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: aurora_service
          uri: http://localhost:9002
          predicates:
            - Path=${app.api-prefix}/aurora/**
          filters:
            - StripPrefix=2
        - id: ai_service
          uri: http://localhost:9003
          predicates:
            - Path=${app.api-prefix}/ai/**
          filters:
            - StripPrefix=2

