spring:
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://identity:9001
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: aurora_service
          uri: http://aurora:9002
          predicates:
            - Path=${app.api-prefix}/aurora/**
          filters:
            - StripPrefix=2
        - id: ai_service
          uri: http://localhost:9003
          predicates:
            - Path=${app.api-prefix}/ai/**
          filters:
            - StripPrefix=2