FROM gradle:jdk21 AS builder
WORKDIR /builder
COPY ./aurora/build.gradle.kts ./aurora/settings.gradle.kts ./
COPY ./gradle/libs.versions.toml ./gradle/
COPY ./aurora/src ./src
RUN gradle build

FROM eclipse-temurin:21-jre-alpine
EXPOSE 9002
WORKDIR /app
RUN addgroup -g 1000 aurora  \
    && adduser -u 1000 -G aurora -D -H aurora
COPY --from=builder --chown=aurora:aurora /builder/build/libs/*.jar ./aurora.jar
USER aurora
ENTRYPOINT ["java","-jar","./aurora.jar"]