server:
  port: 9001 # must match the port in the Dockerfile
  servlet:
    context-path: /identity
  forward-headers-strategy: framework

spring:
  main:
    banner-mode: off
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://localhost:3306/identity
    username: identity
    password: password
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds